#ifndef ECOSENSEPOWER_PROFILES_H
#define ECOSENSEPOWER_PROFILES_H

#include "core/EcoSensePowerConfig.h"

#if ECOSENSE_ENABLE_PROFILE_CATALOG
#include "profiles/batteries/aa_alkaline.h"
#include "profiles/batteries/cr123a.h"
#include "profiles/batteries/cr2032.h"
#include "profiles/batteries/d_alkaline.h"
#include "profiles/batteries/lifepo4_1s.h"
#include "profiles/batteries/liion_18650.h"
#include "profiles/batteries/lipo_18650.h"
#include "profiles/batteries/lipo_1s.h"
#include "profiles/batteries/lipo_1s_400.h"
#include "profiles/batteries/lipo_2s.h"
#include "profiles/batteries/lipo_2s_2000.h"
#include "profiles/batteries/liso_cl2_aa.h"
#include "profiles/batteries/nimh_aa.h"
#include "profiles/batteries/nimh_aaa.h"
#include "profiles/boards/arduino_mega.h"
#include "profiles/boards/arduino_mkr_wan.h"
#include "profiles/boards/arduino_nano.h"
#include "profiles/boards/arduino_nano_every.h"
#include "profiles/boards/arduino_pro_mini_3v3.h"
#include "profiles/boards/arduino_pro_mini_5v.h"
#include "profiles/boards/attiny85.h"
#include "profiles/boards/avr_uno.h"
#include "profiles/boards/esp32_devkit.h"
#include "profiles/boards/esp32_wroom.h"
#include "profiles/boards/esp8266_nodemcu.h"
#include "profiles/boards/generic_board.h"
#include "profiles/boards/raspberry_pi_pico.h"
#include "profiles/sensors/bme280.h"
#include "profiles/sensors/dht22.h"
#include "profiles/sensors/ds18b20.h"
#include "profiles/sensors/generic_analog.h"
#include "profiles/sensors/hc_sr04.h"
#include "profiles/sensors/ina219.h"
#include "profiles/sensors/ldr_analog.h"
#include "profiles/sensors/mpu6050.h"
#include "profiles/sensors/pir_generic.h"
#include "profiles/sensors/scd30.h"
#include "profiles/sensors/soil_resistive.h"
#include "profiles/radios/esp8266_wifi.h"
#include "profiles/radios/hc12.h"
#include "profiles/radios/nrf24l01.h"
#include "profiles/radios/rfm95w.h"
#include "profiles/radios/sim800l.h"
#include "profiles/radios/sx1276_lora.h"
#include "EcoSensePowerBluetoothProfiles.h"
#include "EcoSensePowerGPSProfiles.h"
#endif

#endif
